type = "2d"
title = "Borealis Ref"
date = [2024, 6, 26]
file = "borealis_ref.png"
alt = "Borealis is a lavender coloured Icewing with pale blue underbelly, and a strip of mint-green scales along his spine with matching spike and purple strips of scales either side."
text = "Refsheet for my oc Borealis!"
tags = ["2024","wof","oc-borealis", "dragon"]