type = "2d"
title = "Moon Moon Ref"
date = [2024, 6, 24]
file = "moon_moon_ref.png"
alt = "Moon Moon is very dark blue Nightwing/Rainwing hybrid with patches of pink and yellow scales across her body and a strip of pink and yellow scales along her spine. Her primary scales (the dark blue) can only change hue, but the pink and yellow scales can change colour as she pleases."
text = "Refsheet for my oc Moon Moon!"
tags = ["2024","wof","oc-moon_moon"]