type = "2d"
title = "Snowreader Ref"
date = [2024, 6, 25]
file = "snowreader_ref.png"
alt = "Snowreader is a dark blue Nightwing/Icewing hybrid, with pale blue underbelly and nested strips of darker blue and light blue scales along his spine with spikes coloured in a gradient from blue to pink. Her wings are covered in star-like spots, and their underside is a light blue."
text = "Refsheet for my oc Snowreader!"
tags = ["2024","wof","oc-snowreader"]