type = "3d"
title = "Low Poly Island"
date = [2024,4,14]
file = "low poly island.png"
alt = "An island floating amongst the stars with visible polygons and a waterfall running down the side, with the Moon hovering in the corner."
tags = ["2025"]
text = "&emsp;This is a lil low-poly island thing i made just to try out some full scenes."