type = "3d"
title = "Nighttime Street"
date = [2024,7,29]
file = "Nighttime Street 1.png"
tags = ["2024"]
text = """
&emsp;This is a scene I made over about a week. I originally meant it for
an Artfight attack, but I didn't finish it in time so now i've just got a
couple nice backgrounds. I'm really happy with how this one turned out, I
got another shot looking down the street as well.
"""