type = "3d"
title = "PFLR_2 Ref"
date = [2024, 6, 29]
file = "pflr_2_ref.png"
alt = "A humanoid robot with silver limbs, and plates of pink-coloured armor over them. Its face is a screen with three glowing blue diamond shapes oriented towards a point in their center."
text = "Refsheet of my OC, PFLR-2!"
tags = ["2024","oc-pflr_2"]